### ISSUE TITLE
Error with set-env command

### ISSUE THREAD

**Issue by mendeljacks** [dibenlloch/google-sheets-secrets-action#10]
I'm getting an error that just started recently after some github action updates.

Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Could it be this library needs to just be updated to use a later version of @actions/core?

**Comment by dibenlloch** [comment]
Hi @mendeljacks, thanks for your report.
Fixed it on 1.0.2 version, let me know if there are any issues
